=== chummer5a/chummer5a/Chummer/data/critterpowers.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
<xs:include schemaLocation="../data../bonuses.xsd" />
  
  <xs:element name="chummer">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="version" type="xs:string" minOccurs="0" />
        <xs:element name="categories" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="category" nillable="true" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent msdata:ColumnName="category_Text" msdata:Ordinal="0">
                    <xs:extension base="xs:string">
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="powers" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="power" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="id" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="category" type="xs:string" minOccurs="1" maxOccurs="1" />
					<xs:element name="toxic" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="rating" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="type" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="action" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="range" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="duration" type="xs:string" minOccurs="1" maxOccurs="1" />
					<xs:element name="bonus" minOccurs="0" maxOccurs="1" />
                    <xs:element name="source" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="page" type="xs:string" minOccurs="1" maxOccurs="1" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:UseCurrentLocale="true">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="chummer" />
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== chummer5a/chummer5a/Chummer/data/spiritpowers.xml
<?xml version="1.0" encoding="utf-8"?>
<!--This file is part of Chummer5a.

    Chummer5a is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Chummer5a is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Chummer5a.  If not, see <http://www.gnu.org/licenses/>.

    You can obtain the full source code for Chummer5a at
    https://github.com/chummer5a/chummer5a
-->

<chummer xmlns="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/XMLSchema critterpowers.xsd">
  <version>0</version>
  <powers>
    <!--spirit powers corebook-->
    <power>
      <name>Accident</name>
      <source>SR5</source>
      <page>394</page>
    </power>
    <power>
      <name>Animal Control</name>
      <source>SR5</source>
      <page>394</page>
    </power>
    <power>
      <name>Armor</name>
      <source>SR5</source>
      <page>394</page>
    </power>
    <power>
      <name>Astral Form</name>
      <source>SR5</source>
      <page>394</page>
    </power>
    <power>
      <name>Binding</name>
      <source>SR5</source>
      <page>395</page>
    </power>
    <power>
      <name>Compulsion</name>
      <source>SR5</source>
      <page>395</page>
    </power>
    <power>
      <name>Concealment</name>
      <source>SR5</source>
      <page>395</page>
    </power>
    <power>
      <name>Confusion</name>
      <source>SR5</source>
      <page>395</page>
    </power>
    <power>
      <name>Corrosive Spit</name>
      <source>SR5</source>
      <page>395</page>
    </power>
    <power>
      <name>Dragonspeech</name>
      <source>SR5</source>
      <page>395</page>
    </power>
    <power>
      <name>Dual Natured</name>
      <source>SR5</source>
      <page>395</page>
    </power>
    <power>
      <name>Elemental Attack</name>
      <source>SR5</source>
      <page>396</page>
    </power>
    <power>
      <name>Energy Aura</name>
      <source>SR5</source>
      <page>396</page>
    </power>
    <power>
      <name>Engulf</name>
      <source>SR5</source>
      <page>396</page>
    </power>
    <power>
      <name>Enhanced Senses</name>
      <source>SR5</source>
      <page>396</page>
    </power>
    <power>
      <name>Essence Drain</name>
      <source>SR5</source>
      <page>396</page>
    </power>
    <power>
      <name>Fear</name>
      <source>SR5</source>
      <page>397</page>
    </power>
    <power>
      <name>Guard</name>
      <source>SR5</source>
      <page>397</page>
    </power>
    <power>
      <name>Hardened Armor</name>
      <source>SR5</source>
      <page>397</page>
    </power>
    <power>
      <name>Hardened Mystic Armor</name>
      <source>SR5</source>
      <page>397</page>
    </power>
    <power>
      <name>Immunity</name>
      <source>SR5</source>
      <page>397</page>
    </power>
    <power>
      <name>Infection</name>
      <source>SR5</source>
      <page>398</page>
    </power>
    <power>
      <name>Influence</name>
      <source>SR5</source>
      <page>398</page>
    </power>
    <power>
      <name>Innate Spell</name>
      <source>SR5</source>
      <page>398</page>
    </power>
    <power>
      <name>Materialization</name>
      <source>SR5</source>
      <page>398</page>
    </power>
    <power>
      <name>Mimicry</name>
      <source>SR5</source>
      <page>398</page>
    </power>
    <power>
      <name>Mist Form</name>
      <source>SR5</source>
      <page>398</page>
    </power>
    <power>
      <name>Movement</name>
      <source>SR5</source>
      <page>399</page>
    </power>
    <power>
      <name>Mystic Armor</name>
      <source>SR5</source>
      <page>399</page>
    </power>
    <power>
      <name>Natural Weapon</name>
      <source>SR5</source>
      <page>399</page>
    </power>
    <power>
      <name>Noxious Breath</name>
      <source>SR5</source>
      <page>399</page>
    </power>
    <power>
      <name>Paralyzing Howl</name>
      <source>SR5</source>
      <page>399</page>
    </power>
    <power>
      <name>Paralyzing Touch</name>
      <source>SR5</source>
      <page>400</page>
    </power>
    <power>
      <name>Petrification</name>
      <source>SR5</source>
      <page>400</page>
    </power>
    <power>
      <name>Psychokinesis</name>
      <source>SR5</source>
      <page>400</page>
    </power>
    <power>
      <name>Regeneration</name>
      <source>SR5</source>
      <page>400</page>
    </power>
    <power>
      <name>Sapience</name>
      <source>SR5</source>
      <page>400</page>
    </power>
    <power>
      <name>Search</name>
      <source>SR5</source>
      <page>400</page>
    </power>
    <power>
      <name>Venom</name>
      <source>SR5</source>
      <page>401</page>
    </power>
    <power>
      <name>Weather Control</name>
      <source>SR5</source>
      <page>401</page>
    </power>
    <!--spirits power Street Grimoire-->
    <power>
      <name>Anaphylaxis</name>
      <source>SG</source>
      <page>193</page>
    </power>
    <power>
      <name>Astral Gateaway</name>
      <source>SG</source>
      <page>194</page>
    </power>
    <power>
      <name>Aura Masking</name>
      <source>SG</source>
      <page>194</page>
    </power>
    <power>
      <name>Banishing Resistance</name>
      <source>SG</source>
      <page>194</page>
    </power>
    <power>
      <name>Desire Reflection</name>
      <source>SG</source>
      <page>194</page>
    </power>
    <power>
      <name>Deathly Aura</name>
      <source>SG</source>
      <page>194</page>
    </power>
    <power>
      <name>Devouring</name>
      <source>SG</source>
      <page>194</page>
    </power>
    <power>
      <name>Divining</name>
      <source>SG</source>
      <page>194</page>
    </power>
    <power>
      <name>Elemental Attack (Pollutant)</name>
      <source>SG</source>
      <page>195</page>
    </power>
    <power>
      <name>Elemental Attack (Radiation)</name>
      <source>SG</source>
      <page>195</page>
    </power>
    <power>
      <name>Endowment</name>
      <source>SG</source>
      <page>195</page>
    </power>
    <power>
      <name>Energy Drain</name>
      <source>SG</source>
      <page>195</page>
    </power>
    <power>
      <name>Hive Mind</name>
      <source>SG</source>
      <page>195</page>
    </power>
    <power>
      <name>Inhabitation</name>
      <source>SG</source>
      <page>195</page>
    </power>
    <power>
      <name>Magical Guard</name>
      <source>SG</source>
      <page>196</page>
    </power>
    <power>
      <name>Mind Link</name>
      <source>SG</source>
      <page>196</page>
    </power>
    <power>
      <name>Mutagen</name>
      <source>SG</source>
      <page>196</page>
    </power>
    <power>
      <name>Pestilence</name>
      <source>SG</source>
      <page>197</page>
    </power>
    <power>
      <name>Possession</name>
      <source>SG</source>
      <page>197</page>
    </power>
    <power>
      <name>Quake</name>
      <source>SG</source>
      <page>197</page>
    </power>
    <power>
      <name>Realistic Form</name>
      <source>SG</source>
      <page>198</page>
    </power>
    <power>
      <name>Reinforcement</name>
      <source>SG</source>
      <page>198</page>
    </power>
    <power>
      <name>Sense Link</name>
      <source>SG</source>
      <page>198</page>
    </power>
    <power>
      <name>Shadow Cloak</name>
      <source>SG</source>
      <page>198</page>
    </power>
    <power>
      <name>Silence</name>
      <source>SG</source>
      <page>199</page>
    </power>
    <power>
      <name>Sonic Projection</name>
      <source>SG</source>
      <page>199</page>
    </power>
    <power>
      <name>Storm</name>
      <source>SG</source>
      <page>199</page>
    </power>
    <!--sprite powers corebook-->
    <power>
      <name>Camouflage</name>
      <source>SR5</source>
      <page>256</page>
    </power>
    <power>
      <name>Cookie</name>
      <source>SR5</source>
      <page>256</page>
    </power>
    <power>
      <name>Diagnostics</name>
      <source>SR5</source>
      <page>257</page>
    </power>
    <power>
      <name>Storm</name>
      <source>SR5</source>
      <page>256</page>
    </power>
    <power>
      <name>Electron Storm</name>
      <source>SR5</source>
      <page>257</page>
    </power>
    <power>
      <name>Gremlins</name>
      <source>SR5</source>
      <page>257</page>
    </power>
    <power>
      <name>Hash</name>
      <source>SR5</source>
      <page>256</page>
    </power>
    <power>
      <name>Storm</name>
      <source>SR5</source>
      <page>257</page>
    </power>
    <power>
      <name>Stability</name>
      <source>SR5</source>
      <page>257</page>
    </power>
    <power>
      <name>Suppression</name>
      <source>SR5</source>
      <page>257</page>
    </power>
    <power>
      <name>Watermark</name>
      <source>SR5</source>
      <page>257</page>
    </power>
  </powers>
</chummer>
