=== chummer5a/chummer5a/Chummer/data/echoes.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
<xs:include schemaLocation="../data../bonuses.xsd" />
  <xs:include schemaLocation="../data../conditions.xsd" />
  <xs:element name="chummer">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="version" type="xs:string" minOccurs="0" />
        <xs:element name="echoes" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="echo" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
          <xs:element name="id" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="source" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="page" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element ref="bonus" minOccurs="0" maxOccurs="1" />
                    <xs:element ref="forbidden" minOccurs="0" maxOccurs="1" />
                    <xs:element name="limit" type="xs:string" minOccurs="0" />
                    <xs:element ref="required" minOccurs="0" maxOccurs="1" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:UseCurrentLocale="true">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="chummer" />
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== chummer5a/chummer5a/Chummer/data/echoes.xml
<?xml version="1.0" encoding="utf-8"?>

<!--This file is part of Chummer5a.

    Chummer5a is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Chummer5a is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Chummer5a.  If not, see <http://www.gnu.org/licenses/>.

    You can obtain the full source code for Chummer5a at
    https://github.com/chummer5a/chummer5a
-->
<chummer xmlns="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.w3.org/2001/XMLSchema echoes.xsd">
  <version>0</version>
  <echoes>
    <!-- Region Shadowrun 5-->
    <echo>
      <id>36aa9af4-5c04-40d9-ba09-31b401cc1ff0</id>
      <name>Attack Upgrade</name>
      <source>SR5</source>
      <page>258</page>
      <bonus>
        <livingpersona>
          <attack>1</attack>
        </livingpersona>
      </bonus>
      <limit>False</limit>
    </echo>
    <echo>
      <id>cd2e640c-06b7-4638-9eb4-bf75c28452a2</id>
      <name>Data Processing Upgrade</name>
      <source>SR5</source>
      <page>258</page>
      <bonus>
        <livingpersona>
          <dataprocessing>1</dataprocessing>
        </livingpersona>
      </bonus>
      <limit>False</limit>
    </echo>
    <echo>
      <id>4550fe9d-e5da-4b01-8115-14f7a0dfab1c</id>
      <name>Firewall Upgrade</name>
      <source>SR5</source>
      <page>258</page>
      <bonus>
        <livingpersona>
          <firewall>1</firewall>
        </livingpersona>
      </bonus>
      <limit>False</limit>
    </echo>
    <echo>
      <id>13c9f18c-a5f6-40e3-97c1-39265e1d70c2</id>
      <name>Mind Over Machine</name>
      <source>SR5</source>
      <page>258</page>
      <limit>False</limit>
    </echo>
    <echo>
      <id>0adbc66d-6b29-4427-b652-0a93a87804b2</id>
      <name>NeuroFilter</name>
      <source>SR5</source>
      <page>258</page>
      <bonus />
      <limit>False</limit>
    </echo>
    <echo>
      <id>61055141-71f5-400e-9e67-cef650ce4801</id>
      <name>Overclocking</name>
      <source>SR5</source>
      <page>258</page>
      <bonus>
        <matrixinitiativediceadd>1</matrixinitiativediceadd>
      </bonus>
    </echo>
    <echo>
      <id>dbd2fbba-8487-45cc-a92a-33813c3643b6</id>
      <name>Resonance Link</name>
      <source>SR5</source>
      <page>258</page>
    </echo>
    <echo>
      <id>d5dbe3f7-8a44-466b-8d5d-db9f0c68ee6b</id>
      <name>Resonance [Program]</name>
      <source>SR5</source>
      <page>258</page>
      <bonus>
        <selecttext />
      </bonus>
      <limit>False</limit>
    </echo>
    <echo>
      <id>ce98f873-d261-4f1e-8bc7-fafa3c712700</id>
      <name>Sleaze Upgrade</name>
      <source>SR5</source>
      <page>258</page>
      <bonus>
        <livingpersona>
          <sleaze>1</sleaze>
        </livingpersona>
      </bonus>
      <limit>False</limit>
    </echo>
    <!-- End Region -->
    <!-- Region Data Trails -->
    <echo>
      <id>18269d5a-2750-4636-8ae3-f9f268d44577</id>
      <name>Fight or Flight Filter</name>
      <source>DT</source>
      <page>58</page>
      <limit>False</limit>
    </echo>
    <echo>
      <id>e7dc7a5a-89dc-42e4-8332-8225bbff3c45</id>
      <name>Mathemagics</name>
      <source>DT</source>
      <page>58</page>
      <limit>False</limit>
    </echo>
    <echo>
      <id>262dd3e2-5433-4b9a-b637-c5f5a3af5510</id>
      <name>MMRI</name>
      <source>DT</source>
      <page>59</page>
      <limit>False</limit>
    </echo>
    <echo>
      <id>032d5d7f-41b9-47f5-8bd0-b7e2cf2c3adf</id>
      <name>Quiet</name>
      <source>DT</source>
      <page>59</page>
      <limit>False</limit>
    </echo>
    <echo>
      <id>0408da17-8327-4e8c-a64f-48431bba8e58</id>
      <name>Resonance Riding</name>
      <source>DT</source>
      <page>59</page>
      <limit>False</limit>
    </echo>
    <echo>
      <id>e6f66ec1-af07-4008-abbe-e4d31cc82358</id>
      <name>Resonance Scream</name>
      <source>DT</source>
      <page>59</page>
      <limit>False</limit>
    </echo>
    <echo>
      <id>45ed755c-cf0e-4f57-95d2-2c01b4eda760</id>
      <name>Skinlink</name>
      <source>DT</source>
      <page>59</page>
      <limit>False</limit>
    </echo>
    <echo>
      <id>228b8261-deca-4723-b072-0a5135ddef3f</id>
      <name>Sleepwalker</name>
      <source>DT</source>
      <page>59</page>
      <limit>False</limit>
    </echo>
    <echo>
      <id>cee8e3bc-447b-4a67-9752-15e3e104e57d</id>
      <name>Contaminate</name>
      <source>DTD</source>
      <page>165</page>
      <limit>False</limit>
    </echo>
    <echo>
      <id>a0966081-2534-4fc4-a2e6-504b4ecf9756</id>
      <name>Siphon</name>
      <source>DTD</source>
      <page>165</page>
      <limit>False</limit>
    </echo>
    <echo>
      <id>2fe27536-4de7-49c1-a933-8d9a65604533</id>
      <name>Pryon</name>
      <source>DTD</source>
      <page>165</page>
      <limit>False</limit>
    </echo>
    <!-- End Region -->
    <!-- Region Dark Terrors -->
    <echo>
      <id>2c5953bf-3680-4ce5-9087-2e1e419937b2</id>
      <name>Defrag</name>
      <source>DTR</source>
      <page>85</page>
      <limit>False</limit>
    </echo>
    <!-- End Region -->
    <!-- Region Kill Code-->
    <echo>
      <id>64710f70-897a-4505-829d-7d0ade750b24</id>
      <name>Aegis</name>
      <source>KC</source>
      <page>101</page>
    </echo>
    <echo>
      <id>8aa97815-eacb-412d-99ac-1acda562fb52</id>
      <name>Draining Spike</name>
      <source>KC</source>
      <page>101</page>
    </echo>
    <echo>
      <id>a6f9a6cd-4727-4de6-a774-bb93ab67940a</id>
      <name>Neural Synergy</name>
      <source>KC</source>
      <page>101</page>
      <bonus>
        <specificattribute>
          <name>LOG</name>
          <val>1</val>
        </specificattribute>
      </bonus>
      <limit>3</limit>
    </echo>
    <echo>
      <id>96f534c0-b53b-43af-bdac-54de468f0d70</id>
      <name>Predictive Analytics</name>
      <source>KC</source>
      <page>101</page>
      <!-- TODO: Matrix AR Initiative bonus -->
      <limit>4</limit>
    </echo>
    <echo>
      <id>37e8342f-9aad-4ee0-8e68-7a5c00f2678b</id>
      <name>Resonance Resistance</name>
      <source>KC</source>
      <page>102</page>
      <limit>False</limit>
    </echo>
    <echo>
      <id>1e0405f3-3872-4a53-afd7-bd643899e7d9</id>
      <name>The Van der Waals Effect</name>
      <source>KC</source>
      <page>102</page>
      <limit>False</limit>
    </echo>
    <echo>
      <id>6cb9bc65-7b64-44dd-ba9a-f96f3c09c741</id>
      <name>Will of the Resonance</name>
      <source>KC</source>
      <page>102</page>
      <bonus>
        <specificattribute>
          <name>WIL</name>
          <val>1</val>
        </specificattribute>
      </bonus>
      <limit>3</limit>
    </echo>
    <echo>
      <id>f7bd6993-efa4-494c-8c58-e9f0950af7b9</id>
      <name>Daemon: Cyberadept</name>
      <source>KC</source>
      <page>90</page>
      <bonus>
          <cyberadeptdaemon>Rating</cyberadeptdaemon>
      </bonus>
    </echo>
    <!-- End Region -->
  </echoes>
</chummer>
