=== chummer5a/chummer5a/Chummer/data/priorities.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="chummer">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="version" type="xs:unsignedByte" />
        <xs:element name="categories">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="category" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="priorities">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="priority">
                <xs:complexType>
                  <xs:sequence>
                    <xs:choice maxOccurs="unbounded">
                      <xs:element name="id" type="xs:string" />
                      <xs:element name="name" type="xs:string" />
                      <xs:element name="value" type="xs:string" />
                      <xs:element name="category" type="xs:string" />
                      <xs:element name="gameplayoption" type="xs:string" />
                      <xs:element name="skills" type="xs:unsignedByte" />
                      <xs:element name="skillgroups" type="xs:unsignedByte" />
                      <xs:element name="attributes" type="xs:unsignedByte" />
                      <xs:element name="talents">
                        <xs:complexType>
                          <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="talent">
                              <xs:complexType>
                                <xs:sequence>
                                  <xs:element name="name" type="xs:string" />
                                  <xs:element name="value" type="xs:string" />
                                  <xs:element minOccurs="0" name="depth" type="xs:unsignedByte" />
                                  <xs:element minOccurs="0" name="qualities">
                                    <xs:complexType>
                                      <xs:sequence>
                                        <xs:element name="quality" type="xs:string" />
                                      </xs:sequence>
                                    </xs:complexType>
                                  </xs:element>
                                  <xs:element minOccurs="0" name="skillgroupchoices">
                                    <xs:complexType>
                                      <xs:sequence>
                                        <xs:element maxOccurs="unbounded" name="skillgroup" type="xs:string" />
                                      </xs:sequence>
                                    </xs:complexType>
                                  </xs:element>
                                  <xs:element minOccurs="0" name="skillchoices">
                                    <xs:complexType>
                                      <xs:sequence>
                                        <xs:element maxOccurs="unbounded" name="skill" type="xs:string" />
                                      </xs:sequence>
                                    </xs:complexType>
                                  </xs:element>
                                  <xs:element minOccurs="0" name="resonance" type="xs:unsignedByte" />
                                  <xs:element minOccurs="0" name="cfp" type="xs:unsignedByte" />
                                  <xs:element minOccurs="0" name="magic" type="xs:unsignedByte" />
                                  <xs:element minOccurs="0" name="skillgroupqty" type="xs:unsignedByte" />
                                  <xs:element minOccurs="0" name="skillgroupval" type="xs:unsignedByte" />
                                  <xs:element minOccurs="0" name="skillgrouptype" type="xs:string" />
                                  <xs:element minOccurs="0" name="spells" type="xs:unsignedByte" />
                                  <xs:element minOccurs="0" name="skillqty" type="xs:unsignedByte" />
                                  <xs:element minOccurs="0" name="skillval" type="xs:unsignedByte" />
                                  <xs:element minOccurs="0" name="skilltype" type="xs:string" />
                                  <xs:element minOccurs="0" name="required">
                                    <xs:complexType>
                                      <xs:sequence>
                                        <xs:element name="oneof">
                                          <xs:complexType>
                                            <xs:sequence>
                                              <xs:element name="metatype" type="xs:string" />
                                            </xs:sequence>
                                          </xs:complexType>
                                        </xs:element>
                                      </xs:sequence>
                                    </xs:complexType>
                                  </xs:element>
                                  <xs:element minOccurs="0" name="forbidden">
                                    <xs:complexType>
                                      <xs:sequence>
                                        <xs:element name="oneof">
                                          <xs:complexType>
                                            <xs:sequence>
                                              <xs:element name="metatype" type="xs:string" />
                                            </xs:sequence>
                                          </xs:complexType>
                                        </xs:element>
                                      </xs:sequence>
                                    </xs:complexType>
                                  </xs:element>
                                </xs:sequence>
                              </xs:complexType>
                            </xs:element>
                          </xs:sequence>
                        </xs:complexType>
                      </xs:element>
                      <xs:element name="metatypes">
                        <xs:complexType>
                          <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="metatype">
                              <xs:complexType>
                                <xs:sequence>
                                  <xs:element name="name" type="xs:string" />
                                  <xs:element name="value" type="xs:unsignedByte" />
                                  <xs:element name="karma" type="xs:unsignedByte" />
                                  <xs:element minOccurs="0" name="metavariants">
                                    <xs:complexType>
                                      <xs:sequence minOccurs="0">
                                        <xs:element maxOccurs="unbounded" name="metavariant">
                                          <xs:complexType>
                                            <xs:sequence>
                                              <xs:element name="name" type="xs:string" />
                                              <xs:element name="value" type="xs:unsignedByte" />
                                              <xs:element name="karma" type="xs:byte" />
                                            </xs:sequence>
                                          </xs:complexType>
                                        </xs:element>
                                      </xs:sequence>
                                    </xs:complexType>
                                  </xs:element>
                                </xs:sequence>
                              </xs:complexType>
                            </xs:element>
                          </xs:sequence>
                        </xs:complexType>
                      </xs:element>
                      <xs:element name="resources" type="xs:unsignedInt" />
                    </xs:choice>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== chummer5a/chummer5a/Chummer/Custom Content/Technomancer Errata/override_technomancer_errata_priorities.xml
<!--This file is part of Chummer5a.

    Chummer5a is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Chummer5a is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Chummer5a.  If not, see <http://www.gnu.org/licenses/>.

    You can obtain the full source code for Chummer5a at
    https://github.com/chummer5a/chummer5a
-->
<chummer xmlns="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/XMLSchema ../data/priorities.xsd">
  <version>0</version>
  <categories>
    <category>Heritage</category>
    <category>Talent</category>
    <category>Attributes</category>
    <category>Skills</category>
    <category>Resources</category>
  </categories>
  <priorities>
    <!-- Region Talents -->
    <priority>
      <id>9d58a295-7c59-4d3f-8001-a5565da6b836</id>
      <name>A - Magician or Technomancer</name>
      <value>A,4</value>
      <category>Talent</category>
      <talents>
        <talent>
          <name>Magician - 6 Magic/10 Spells</name>
          <value>Magician</value>
          <qualities>
            <quality>Magician</quality>
          </qualities>
          <magic>6</magic>
          <spells>10</spells>
          <skillqty>2</skillqty>
          <skillval>5</skillval>
          <skilltype>magic</skilltype>
          <forbidden>
            <oneof>
              <metatype>A.I.</metatype>
            </oneof>
          </forbidden>
        </talent>
        <talent>
          <name>Mystic Adept - 6 Magic/10 Spells</name>
          <value>Mystic Adept</value>
          <qualities>
            <quality>Mystic Adept</quality>
          </qualities>
          <magic>6</magic>
          <spells>10</spells>
          <skillqty>2</skillqty>
          <skillval>5</skillval>
          <skilltype>magic</skilltype>
          <forbidden>
            <oneof>
              <metatype>A.I.</metatype>
            </oneof>
          </forbidden>
        </talent>
        <talent>
          <name>Technomancer - 6 Resonance/7 Complex Forms</name>
          <value>Technomancer</value>
          <qualities>
            <quality>Technomancer</quality>
          </qualities>
          <skillchoices>
            <skill>Compiling</skill>
            <skill>Decompiling</skill>
            <skill>Registering</skill>
            <skill>Computer</skill>
            <skill>Hardware</skill>
            <skill>Software</skill>
            <skill>Cybercombat</skill>
            <skill>Electronic Warfare</skill>
            <skill>Hacking</skill>
          </skillchoices>
          <resonance>6</resonance>
          <cfp>7</cfp>
          <skillqty>3</skillqty>
          <skillval>5</skillval>
          <skilltype>specific</skilltype>
          <forbidden>
            <oneof>
              <metatype>A.I.</metatype>
            </oneof>
          </forbidden>
        </talent>
        <talent>
          <name>AI - 6 Depth</name>
          <value>A.I.</value>
          <depth>6</depth>
          <skillqty>2</skillqty>
          <skillval>5</skillval>
          <skilltype>matrix</skilltype>
          <required>
            <oneof>
              <metatype>A.I.</metatype>
            </oneof>
          </required>
        </talent>
      </talents>
    </priority>
    <priority>
      <id>774fd89a-ecea-4f5f-ad2b-c4476ca46f70</id>
      <name>B - Adept, Magician, or Technomancer</name>
      <value>B,3</value>
      <category>Talent</category>
      <talents>
        <talent>
          <name>Adept - 6 Magic</name>
          <value>Adept</value>
          <qualities>
            <quality>Adept</quality>
          </qualities>
          <magic>6</magic>
          <skillqty>1</skillqty>
          <skillval>4</skillval>
          <skilltype>active</skilltype>
          <forbidden>
            <oneof>
              <metatype>A.I.</metatype>
            </oneof>
          </forbidden>
        </talent>
        <talent>
          <name>Magician - 4 Magic/7 Spells</name>
          <value>Magician</value>
          <qualities>
            <quality>Magician</quality>
          </qualities>
          <magic>4</magic>
          <spells>7</spells>
          <skillqty>2</skillqty>
          <skillval>4</skillval>
          <skilltype>magic</skilltype>
          <forbidden>
            <oneof>
              <metatype>A.I.</metatype>
            </oneof>
          </forbidden>
        </talent>
        <talent>
          <name>Mystic Adept - 4 Magic/7 Spells</name>
          <value>Mystic Adept</value>
          <qualities>
            <quality>Mystic Adept</quality>
          </qualities>
          <magic>4</magic>
          <spells>7</spells>
          <skillqty>2</skillqty>
          <skillval>4</skillval>
          <skilltype>magic</skilltype>
          <forbidden>
            <oneof>
              <metatype>A.I.</metatype>
            </oneof>
          </forbidden>
        </talent>
        <talent>
          <name>Aspected Magician - 5 Magic</name>
          <value>Aspected Magician</value>
          <qualities>
            <quality>Aspected Magician</quality>
          </qualities>
          <skillgroupchoices>
            <skillgroup>Conjuring</skillgroup>
            <skillgroup>Enchanting</skillgroup>
            <skillgroup>Sorcery</skillgroup>
          </skillgroupchoices>
          <magic>5</magic>
          <skillgroupqty>1</skillgroupqty>
          <skillgroupval>4</skillgroupval>
          <skillgrouptype>choices</skillgrouptype>
          <forbidden>
            <oneof>
              <metatype>A.I.</metatype>
            </oneof>
          </forbidden>
        </talent>
        <talent>
          <name>Apprentice - 5 Magic</name>
          <value>Apprentice</value>
          <qualities>
            <quality>Apprentice</quality>
          </qualities>
          <magic>5</magic>
          <forbidden>
            <oneof>
              <metatype>A.I.</metatype>
            </oneof>
          </forbidden>
        </talent>
        <talent>
          <name>Technomancer - 4 Resonance/4 Complex Forms</name>
          <value>Technomancer</value>
          <qualities>
            <quality>Technomancer</quality>
          </qualities>
          <skillchoices>
            <skill>Compiling</skill>
            <skill>Decompiling</skill>
            <skill>Registering</skill>
            <skill>Computer</skill>
            <skill>Hardware</skill>
            <skill>Software</skill>
            <skill>Cybercombat</skill>
            <skill>Electronic Warfare</skill>
            <skill>Hacking</skill>
          </skillchoices>
          <resonance>4</resonance>
          <cfp>4</cfp>
          <skillqty>3</skillqty>
          <skillval>4</skillval>
          <skilltype>specific</skilltype>
          <forbidden>
            <oneof>
              <metatype>A.I.</metatype>
            </oneof>
          </forbidden>
        </talent>
        <talent>
          <name>AI - 4 Depth</name>
          <value>AI</value>
          <depth>4</depth>
          <skillqty>2</skillqty>
          <skillval>4</skillval>
          <skilltype>matrix</skilltype>
          <required>
            <oneof>
              <metatype>A.I.</metatype>
            </oneof>
          </required>
        </talent>
      </talents>
    </priority>
    <priority>
      <id>aae3a140-d306-4811-a9d2-874140600150</id>
      <name>C - Adept, Magician, or Technomancer</name>
      <value>C,2</value>
      <category>Talent</category>
      <talents>
        <talent>
          <name>Adept - 4 Magic</name>
          <value>Adept</value>
          <qualities>
            <quality>Adept</quality>
          </qualities>
          <magic>4</magic>
          <skillqty>1</skillqty>
          <skillval>2</skillval>
          <skilltype>active</skilltype>
          <forbidden>
            <oneof>
              <metatype>A.I.</metatype>
            </oneof>
          </forbidden>
        </talent>
        <talent>
          <name>Magician - 3 Magic/5 Spells</name>
          <value>Magician</value>
          <qualities>
            <quality>Magician</quality>
          </qualities>
          <magic>3</magic>
          <spells>5</spells>
          <forbidden>
            <oneof>
              <metatype>A.I.</metatype>
            </oneof>
          </forbidden>
        </talent>
        <talent>
          <name>Mystic Adept - 3 Magic/5 Spells</name>
          <value>Mystic Adept</value>
          <qualities>
            <quality>Mystic Adept</quality>
          </qualities>
          <magic>3</magic>
          <spells>5</spells>
          <forbidden>
            <oneof>
              <metatype>A.I.</metatype>
            </oneof>
          </forbidden>
        </talent>
        <talent>
          <name>Aspected Magician - 3 Magic</name>
          <value>Aspected Magician</value>
          <qualities>
            <quality>Aspected Magician</quality>
          </qualities>
          <skillgroupchoices>
            <skillgroup>Conjuring</skillgroup>
            <skillgroup>Enchanting</skillgroup>
            <skillgroup>Sorcery</skillgroup>
          </skillgroupchoices>
          <magic>3</magic>
          <skillgroupqty>1</skillgroupqty>
          <skillgroupval>2</skillgroupval>
          <skillgrouptype>choices</skillgrouptype>
          <forbidden>
            <oneof>
              <metatype>A.I.</metatype>
            </oneof>
          </forbidden>
        </talent>
        <talent>
          <name>Explorer - 5 Magic</name>
          <value>Explorer</value>
          <qualities>
