=== chummer5a/chummer5a/Chummer/data/qualities.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="bonuses.xsd" />
  <xs:include schemaLocation="conditions.xsd" />
  <xs:element name="chummer">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="version" type="xs:string" minOccurs="0" />
        <xs:element name="categories" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="category" nillable="true" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="qualities" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="quality" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="id" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="karma" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="category" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="addqualities" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="addquality" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute name="contributetobp" type="xs:boolean" use="optional" />
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="addweapon" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
                    <xs:element name="canbuywithspellpoints" minOccurs="0" maxOccurs="1" />
                    <xs:element name="careeronly" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="chargenlimit" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="chargenonly" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="contributetolimit" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="costdiscount" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element ref="required" minOccurs="1" maxOccurs="1" />
                          <xs:element name="value" type="xs:integer" minOccurs="1" maxOccurs="1" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="critterpowers" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="power" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute name="select" type="xs:string" use="optional" />
                                  <xs:attribute name="rating" type="xs:string" use="optional" />
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="doublecareer" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="hide" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="implemented" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="includeinlimit" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="limit" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="limitwithinclusions" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="metagenetic" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="mutant" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="naturalweapons" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="naturalweapon" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
                                <xs:element name="reach" type="xs:string" minOccurs="1" maxOccurs="1" />
                                <xs:element name="damage" type="xs:string" minOccurs="1" maxOccurs="1" />
                                <xs:element name="ap" type="xs:string" minOccurs="1" maxOccurs="1" />
                                <xs:element name="useskill" type="xs:string" minOccurs="1" maxOccurs="1" />
                                <xs:element name="accuracy" type="xs:string" minOccurs="1" maxOccurs="1" />
                                <xs:element name="source" type="xs:string" minOccurs="1" maxOccurs="1" />
                                <xs:element name="page" type="xs:string" minOccurs="1" maxOccurs="1" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="nolevels" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="onlyprioritygiven" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="powers" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="power" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="print" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="refundkarmaonremove" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="stagedpurchase" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="bonus" type="bonusTypes"  minOccurs="0" maxOccurs="1"/>
                    <xs:element name="firstlevelbonus" type="bonusTypes"  minOccurs="0" maxOccurs="1"/>
                    <xs:element ref="forbidden" minOccurs="0" maxOccurs="1" />
                    <xs:element ref="required" minOccurs="0" maxOccurs="1" />
                    <xs:element name="source" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="page" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="nameonpage" type="xs:string" minOccurs="0" maxOccurs="1" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== chummer5a/chummer5a/Chummer/customdata/ShadowNET Rules/amend_qualities.xml
<?xml version="1.0" encoding="utf-8"?>
<!--This file is part of Chummer5a.

    Chummer5a is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Chummer5a is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Chummer5a.  If not, see <http://www.gnu.org/licenses />.

    You can obtain the full source code for Chummer5a at
    https://github.com/chummer5a/chummer5a
-->
<chummer xmlns="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/XMLSchema qualities.xsd">
  <!--Region Shadowrun Core Positive Qualities -->
  <qualities>
    <!--Region Bullets and Bandages Negative Qualities -->
    <quality>
      <name>Pregnant</name>
      <hide />
    </quality>
    <!-- End Region-->
    <!--Region Sail Away, Sweet Sister Positive Qualities -->
<!--    <quality>
      <name>College Education</name>
      <hide />
    </quality>
    <quality>
      <name>Inspired</name>
      <hide />
    </quality> -->
    <!-- End Region-->
    <!--Region Run Faster -->
    <!--Region Run Faster Positive Qualities -->
    <quality>
      <name>Changeling (Class I SURGE)</name>
      <hide />
    </quality>
    <quality>
      <name>Changeling (Class II SURGE)</name>
      <hide />
    </quality>
    <quality>
      <name>Friends in High Places</name>
      <hide />
    </quality>
    <!-- End Region-->
    <!--Region Run Faster Negative Qualities -->
<!--    <quality>
      <name>Amnesia (Surface Loss)</name>
      <hide />
    </quality> -->
    <quality>
      <name>Amnesia (Neural Deletion)</name>
      <hide />
    </quality>
    <quality>
      <name>Carrier (HMHVV Strain II)</name>
      <hide />
    </quality>
    <quality>
      <name>Carrier (HMHVV Strain III)</name>
      <hide />
    </quality>
    <quality>
      <name>Day Job (10 hrs)</name>
      <hide />
    </quality>
    <quality>
      <name>Day Job (20 hrs)</name>
      <hide />
    </quality>
    <quality>
      <name>Day Job (40 hrs)</name>
      <hide />
    </quality>
    <quality>
      <name>Hung Out to Dry</name>
      <hide />
    </quality>
    <quality>
      <name>In Debt</name>
      <hide />
    </quality>
    <!-- End Region -->
    <!-- Region Run Faster Infected Qualities -->
    <quality>
      <name>Infected: Loup-Garou</name>
      <hide />
    </quality>
    <quality>
      <name>Infected: Mutaqua</name>
      <hide />
    </quality>
    <quality>
      <name>Infected: Nosferatu</name>
      <hide />
    </quality>
    <!-- End Region -->
    <!-- End Region -->
    <!-- Region Data Trails-->
    <!--Region Data Trails Positive Qualities -->
    <quality>
      <name>Chatty</name>
      <hide />
    </quality>
    <quality>
      <name>Designer</name>
      <hide />
    </quality>
    <quality>
      <name>Exceptional Entity</name>
      <hide />
    </quality>
    <quality>
      <name>Hello World!</name>
      <hide />
    </quality>
    <quality>
      <name>Inherent Program</name>
      <hide />
    </quality>
    <quality>
      <name>Improved Restoration</name>
      <hide />
    </quality>
    <quality>
      <name>Low Profile</name>
      <hide />
    </quality>
    <quality>
      <name>Munge</name>
      <hide />
    </quality>
    <quality>
      <name>Multiprocessing</name>
      <hide />
    </quality>
    <quality>
      <name>Pilot Origins</name>
      <hide />
    </quality>
    <quality>
      <name>Redundancy</name>
      <hide />
    </quality>
    <quality>
      <name>Sapper</name>
      <hide />
    </quality>
    <quality>
      <name>Sensor Upgrade</name>
      <hide />
    </quality>
    <quality>
      <name>Snooper</name>
      <hide />
    </quality>
    <quality>
      <name>Virtual Stability</name>
      <hide />
    </quality>
    <!-- End Region -->
    <!--Region Data Trails Negative Qualities -->
    <quality>
      <name>Corrupter</name>
      <hide />
    </quality>
    <quality>
      <name>Easily Exploitable</name>
      <hide />
    </quality>
    <quality>
      <name>Fragmentation</name>
      <hide />
    </quality>
    <quality>
      <name>Persnickety Renter</name>
      <hide />
    </quality>
    <quality>
      <name>Real World Naivet√©</name>
      <hide />
    </quality>
    <!-- End Region -->
    <!-- End Region -->
    <!-- Region Chrome Flesh -->
    <!--Region Chrome Flesh Positive Qualities -->
    <quality>
      <name>Better to be Feared Than Loved</name>
      <hide />
    </quality>
    <quality>
      <name>Revels in Murder</name>
      <hide />
    </quality>
    <!-- End Region -->
    <!--Region Chrome Flesh Negative Qualities -->
    <quality>
      <name>Blank Slate</name>
      <hide />
    </quality>
<!--    <quality>
      <name>Cyber-snob</name>
      <hide />
    </quality> -->
    <quality>
      <name>Dead Emotion</name>
      <hide />
    </quality>
    <quality>
      <name>One of Them</name>
      <hide />
    </quality>
    <quality>
      <name>So Jacked Up</name>
      <hide />
    </quality>
    <quality>
      <name>Tough and Targeted</name>
      <hide />
    </quality>
    <!-- End Region -->
    <!-- End Region -->
    <!-- Region Hard Targets -->
    <!-- Region Hard Targets Negative Qualities-->
    <!-- End Region -->
    <!-- End Region -->
    <!-- Region Rigger 5.0-->
    <!-- Region Negative Qualities -->
    <!-- End Region -->
    <!-- End Region -->
    <!-- Region Howling Shadows -->
    <quality>
      <name>Latent Dracomorphosis</name>
      <hide />
    </quality>
    <quality>
      <name>Dracoform (Eastern Drake)</name>
      <hide />
    </quality>
    <quality>
      <name>Dracoform (Western Drake)</name>
      <hide />
    </quality>
    <quality>
      <name>Dracoform (Feathered Drake)</name>
      <hide />
    </quality>
    <quality>
      <name>Dracoform (Sea Drake)</name>
      <hide />
    </quality>
    <!-- End Region -->
    <!-- Region Cutting Aces -->
    <!-- Region Negative Qualities -->
    <!-- End Region -->
    <!-- End Region -->
    <!-- Region Forbidden Arcana -->
    <!-- Region Mastery Qualities -->
    <quality>
      <name>Archivist</name>
      <hide />
    </quality>
    <quality>
      <name>Astral Bouncer</name>
      <hide />
    </quality>
    <quality>
      <name>Barehanded Adept</name>
      <hide />
    </quality>
    <quality>
      <name>Blood Necromancer</name> <!-- Player Only -->
      <hide />
    </quality>
    <quality>
      <name>Chain Breaker</name>
      <hide />
    </quality>
    <quality>
      <name>Chosen Follower</name>
      <hide />
    </quality>
    <quality>
      <name>Crystal Breath</name>
      <hide />
    </quality>
    <quality>
      <name>Crystal Eye (One Eye)</name>
      <hide />
    </quality>
	<quality>
      <name>Crystal Eye (Two Eyes)</name>
      <hide />
    </quality>
    <quality>
      <name>Crystal Gut (Liver)</name>
      <hide />
    </quality>
	<quality>
      <name>Crystal Gut (Kidneys)</name>
      <hide />
    </quality>
	<quality>
      <name>Crystal Gut (Stomach)</name>
      <hide />
    </quality>
	<quality>
      <name>Crystal Gut (Intestines)</name>
      <hide />
    </quality>
	<quality>
      <name>Crystal Gut (Liver, Kidneys)</name>
      <hide />
    </quality>
	<quality>
      <name>Crystal Gut (Liver, Stomach)</name>
      <hide />
    </quality>
	<quality>
      <name>Crystal Gut (Liver, Intestines)</name>
      <hide />
    </quality>
	<quality>
      <name>Crystal Gut (Kidneys, Stomach)</name>
      <hide />
    </quality>
	<quality>
      <name>Crystal Gut (Kidneys, Intestines)</name>
      <hide />
    </quality>
	<quality>
      <name>Crystal Gut (Stomach, Intestines)</name>
      <hide />
    </quality>
	<quality>
      <name>Crystal Gut (Liver, Kidneys, Stomach)</name>
      <hide />
    </quality>
	<quality>
      <name>Crystal Gut (Liver, Kidneys, Intestines)</name>
      <hide />
    </quality>
	<quality>
      <name>Crystal Gut (Liver, Stomach, Intestines)</name>
      <hide />
    </quality>
	<quality>
      <name>Crystal Gut (Kidneys, Stomach, Intestines)</name>
      <hide />
    </quality>
	<quality>
      <name>Crystal Gut (Liver, Kidneys, Stomach, Intestines)</name>
      <hide />
    </quality>
    <quality>
      <name>Crystal Jaw</name>
      <hide />
    </quality>
    <quality>
      <name>Crystal Limb (Arm)</name>
      <hide />
    </quality>
    <quality>
      <name>Crystal Limb (Leg)</name>
      <hide />
    </quality>
    <quality>
      <name>Crystal Spine</name>
      <hide />
    </quality>
    <quality>
      <name>Crystalline Blade</name>
      <hide />
    </quality>
    <quality>
      <name>Crystalline Claws</name>
      <hide />
    </quality>
    <quality>
      <name>Crystalline Diver</name>
      <hide />
    </quality>
    <quality>
      <name>Crystalline Grace</name>
      <hide />
    </quality>
    <quality>
      <name>Crystalline Reflexes</name>
      <hide />
    </quality>
    <quality>
      <name>Crystalline Shards</name>
      <hide />
    </quality>
    <quality>
      <name>Crystalline Vision</name>
      <hide />
    </quality>
    <quality>
      <name>Dark Ally</name> <!-- Player Only -->
      <hide />
    </quality>
    <quality>
      <name>Elemental Master</name>
      <hide />
    </quality>
    <quality>
      <name>Human Lifespan</name> <!-- Not in Player Rules -->
      <hide />
    </quality>
    <quality>
      <name>Mystic Foreman</name>
      <hide />
    </quality>
    <quality>
      <name>Puppet Master</name>
      <hide />
    </quality>
    <quality>
      <name>Shock Mage</name>
