=== chummer5a/chummer5a/Chummer/data/spells.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
<xs:include schemaLocation="../data../bonuses.xsd" />
<xs:include schemaLocation="../data../conditions.xsd" />
  <xs:element name="chummer">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="version" type="xs:string" minOccurs="0" />
        <xs:element name="categories" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="category" nillable="true" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent msdata:ColumnName="category_Text" msdata:Ordinal="0">
                    <xs:extension base="xs:string">
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="spells" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="spell" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="id" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="page" type="xs:string" minOccurs="1" maxOccurs="1" />
          <xs:element name="source" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="category" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="damage" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="descriptor" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="duration" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="dv" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="range" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="type" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element ref="bonus" minOccurs="0" maxOccurs="1" />
                    <xs:element ref="forbidden" minOccurs="0" maxOccurs="1" />
                    <xs:element ref="required" minOccurs="0" maxOccurs="1" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:UseCurrentLocale="true">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="chummer" />
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== chummer5a/chummer5a/Chummer/data/spells.xml
<?xml version="1.0" encoding="utf-8"?>

<!--This file is part of Chummer5a.

    Chummer5a is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Chummer5a is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Chummer5a.  If not, see <http://www.gnu.org/licenses/>.

    You can obtain the full source code for Chummer5a at
    https://github.com/chummer5a/chummer5a
-->
<chummer xmlns="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.w3.org/2001/XMLSchema spells.xsd">

  <categories>
    <category useskill="Spellcasting" alchemicalskill="Alchemy" barehandedadeptskill="Unarmed Combat">Combat</category>
    <category useskill="Spellcasting" alchemicalskill="Alchemy" barehandedadeptskill="Unarmed Combat">Detection</category>
    <category useskill="Spellcasting" alchemicalskill="Alchemy" barehandedadeptskill="Unarmed Combat">Health</category>
    <category useskill="Spellcasting" alchemicalskill="Alchemy" barehandedadeptskill="Unarmed Combat">Illusion</category>
    <category useskill="Spellcasting" alchemicalskill="Alchemy" barehandedadeptskill="Unarmed Combat">Manipulation</category>
    <category useskill="Artificing">Enchantments</category>
    <category useskill="Ritual Spellcasting">Rituals</category>
  </categories>
  <spells>
    <!-- Region SR5 -->
    <spell>
      <id>c78d91cc-fa02-48c3-a243-28823a2038ef</id>
      <name>Acid Stream</name>
      <page>283</page>
      <source>SR5</source>
      <category>Combat</category>
      <damage>P</damage>
      <descriptor>Indirect, Elemental</descriptor>
      <duration>I</duration>
      <dv>F-3</dv>
      <range>LOS</range>
      <type>P</type>
    </spell>
    <spell>
      <id>87cb3685-22e8-46fa-890f-f3cfef10a71f</id>
      <name>Toxic Wave</name>
      <page>283</page>
      <source>SR5</source>
      <category>Combat</category>
      <damage>P</damage>
      <descriptor>Indirect, Elemental, Area</descriptor>
      <duration>I</duration>
      <dv>F-1</dv>
      <range>LOS (A)</range>
      <type>P</type>
    </spell>
    <spell>
      <id>10dd2924-36c6-42a3-8715-694c29c1fd48</id>
      <name>Punch</name>
      <page>283</page>
      <source>SR5</source>
      <category>Combat</category>
      <damage>S</damage>
      <descriptor>Indirect</descriptor>
      <duration>I</duration>
      <dv>F-6</dv>
      <range>T</range>
      <type>P</type>
    </spell>
    <spell>
      <id>241b9811-e7d8-41d5-b4cc-444e599599fc</id>
      <name>Clout</name>
      <page>284</page>
      <source>SR5</source>
      <category>Combat</category>
      <damage>S</damage>
      <descriptor>Indirect</descriptor>
      <duration>I</duration>
      <dv>F-3</dv>
      <range>LOS</range>
      <type>P</type>
    </spell>
    <spell>
      <id>187b1ffe-470c-4672-ba9d-376ee1856a1c</id>
      <name>Blast</name>
      <page>284</page>
      <source>SR5</source>
      <category>Combat</category>
      <damage>S</damage>
      <descriptor>Indirect, Area</descriptor>
      <duration>I</duration>
      <dv>F</dv>
      <range>LOS (A)</range>
      <type>P</type>
    </spell>
    <spell>
      <id>9baed162-5e84-4f19-9b94-d543a560c067</id>
      <name>Death Touch</name>
      <page>284</page>
      <source>SR5</source>
      <category>Combat</category>
      <damage>P</damage>
      <descriptor>Direct</descriptor>
      <duration>I</duration>
      <dv>F-6</dv>
      <range>T</range>
      <type>M</type>
    </spell>
    <spell>
      <id>85c12bae-3954-483c-a211-d8ee43a1c65e</id>
      <name>Manabolt</name>
      <page>284</page>
      <source>SR5</source>
      <category>Combat</category>
      <damage>P</damage>
      <descriptor>Direct</descriptor>
      <duration>I</duration>
      <dv>F-3</dv>
      <range>LOS</range>
      <type>M</type>
    </spell>
    <spell>
      <id>d866f612-7160-41d2-8ce9-b64262327559</id>
      <name>Manaball</name>
      <page>284</page>
      <source>SR5</source>
      <category>Combat</category>
      <damage>P</damage>
      <descriptor>Direct, Area</descriptor>
      <duration>I</duration>
      <dv>F</dv>
      <range>LOS (A)</range>
      <type>M</type>
    </spell>
    <spell>
      <id>02de7f2a-3c8e-48a5-b7d1-0bf9854271aa</id>
      <name>Flamethrower</name>
      <page>284</page>
      <source>SR5</source>
      <category>Combat</category>
      <damage>P</damage>
      <descriptor>Indirect, Elemental</descriptor>
      <duration>I</duration>
      <dv>F-3</dv>
      <range>LOS</range>
      <type>P</type>
    </spell>
    <spell>
      <id>9ce1e699-3c30-4184-858b-d5539935ef96</id>
      <name>Fireball</name>
      <page>284</page>
      <source>SR5</source>
      <category>Combat</category>
      <damage>P</damage>
      <descriptor>Indirect, Elemental, Area</descriptor>
      <duration>I</duration>
      <dv>F-1</dv>
      <range>LOS (A)</range>
      <type>P</type>
    </spell>
    <spell>
      <id>b39ec682-8409-4546-be00-7615583e6541</id>
      <name>Lightning Bolt</name>
      <page>284</page>
      <source>SR5</source>
      <category>Combat</category>
      <damage>P</damage>
      <descriptor>Indirect, Elemental</descriptor>
      <duration>I</duration>
      <dv>F-3</dv>
      <range>LOS</range>
      <type>P</type>
    </spell>
    <spell>
      <id>9b5c1538-d66b-4b71-9953-78817aaef6e4</id>
      <name>Ball Lightning</name>
      <page>284</page>
      <source>SR5</source>
      <category>Combat</category>
      <damage>P</damage>
      <descriptor>Indirect, Elemental, Area</descriptor>
      <duration>I</duration>
      <dv>F-1</dv>
      <range>LOS (A)</range>
      <type>P</type>
    </spell>
    <spell>
      <id>92467147-ce2c-480e-b4e0-f4a269c2ad86</id>
      <name>Shatter</name>
      <page>284</page>
      <source>SR5</source>
      <category>Combat</category>
      <damage>P</damage>
      <descriptor>Direct</descriptor>
      <duration>I</duration>
      <dv>F-6</dv>
      <range>T</range>
      <type>P</type>
    </spell>
    <spell>
      <id>a7f17805-3e3e-4a12-8580-b9de0d7499ef</id>
      <name>Powerbolt</name>
      <page>284</page>
      <source>SR5</source>
      <category>Combat</category>
      <damage>P</damage>
      <descriptor>Direct</descriptor>
      <duration>I</duration>
      <dv>F-3</dv>
      <range>LOS</range>
      <type>P</type>
    </spell>
    <spell>
      <id>1e25e684-9eec-4d1a-acac-488c8c00c24f</id>
      <name>Powerball</name>
      <page>284</page>
      <source>SR5</source>
      <category>Combat</category>
      <damage>P</damage>
      <descriptor>Direct, Area</descriptor>
      <duration>I</duration>
      <dv>F</dv>
      <range>LOS (A)</range>
      <type>P</type>
    </spell>
    <spell>
      <id>6cbe13c4-ef28-43b7-9715-bccb7c153999</id>
      <name>Knockout</name>
      <page>284</page>
      <source>SR5</source>
      <category>Combat</category>
      <damage>S</damage>
      <descriptor>Direct</descriptor>
      <duration>I</duration>
      <dv>F-6</dv>
      <range>T</range>
      <type>M</type>
    </spell>
    <spell>
      <id>47423962-6b73-4cc3-ad4e-e8d037cf9507</id>
      <name>Stunbolt</name>
      <page>284</page>
      <source>SR5</source>
      <category>Combat</category>
      <damage>S</damage>
      <descriptor>Direct</descriptor>
      <duration>I</duration>
      <dv>F-3</dv>
      <range>LOS</range>
      <type>M</type>
    </spell>
    <spell>
      <id>e9f1e14b-1f59-46d6-9e9f-e808d7316d76</id>
      <name>Stunball</name>
      <page>284</page>
      <source>SR5</source>
      <category>Combat</category>
      <damage>S</damage>
      <descriptor>Direct, Area</descriptor>
      <duration>I</duration>
      <dv>F</dv>
      <range>LOS (A)</range>
      <type>M</type>
    </spell>
    <spell>
      <id>e81dda32-1c97-482b-a6a5-ddd12eded03a</id>
      <name>Analyze Device</name>
      <page>285</page>
      <source>SR5</source>
      <category>Detection</category>
      <damage>0</damage>
      <descriptor>Active, Directional</descriptor>
      <duration>S</duration>
      <dv>F-3</dv>
      <range>T</range>
      <type>P</type>
    </spell>
    <spell>
      <id>4828522d-848c-4ebe-850e-fa3f3babf241</id>
      <name>Analyze Magic</name>
      <page>285</page>
      <source>SR5</source>
      <category>Detection</category>
      <damage>0</damage>
      <descriptor>Active, Directional</descriptor>
      <duration>S</duration>
      <dv>F-3</dv>
      <range>T</range>
      <type>P</type>
    </spell>
    <spell>
      <id>933a534c-ad50-4c87-be65-2230d56f5fcd</id>
      <name>Analyze Truth</name>
      <page>286</page>
      <source>SR5</source>
      <category>Detection</category>
      <damage>0</damage>
      <descriptor>Active, Directional</descriptor>
      <duration>S</duration>
      <dv>F-2</dv>
      <range>T</range>
      <type>M</type>
    </spell>
    <spell>
      <id>fb44d690-17c0-4d22-819e-8b7b463b2599</id>
      <name>Clairaudience</name>
      <page>286</page>
      <source>SR5</source>
      <category>Detection</category>
      <damage>0</damage>
      <descriptor>Passive, Directional</descriptor>
      <duration>S</duration>
      <dv>F-3</dv>
      <range>T</range>
      <type>M</type>
    </spell>
    <spell>
      <id>d82c56f8-9231-48a9-9dea-dea6c513caad</id>
      <name>Clairvoyance</name>
      <page>286</page>
      <source>SR5</source>
      <category>Detection</category>
      <damage>0</damage>
      <descriptor>Passive, Directional</descriptor>
      <duration>S</duration>
      <dv>F-3</dv>
      <range>T</range>
      <type>M</type>
    </spell>
    <spell>
