=== chummer5a/chummer5a/Chummer/data/streams.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
  <xs:element name="chummer">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="version" type="xs:string" minOccurs="0" />
        <xs:element name="traditions" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="tradition" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="id" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="drain" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="spirits" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="spirit" nillable="true" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:simpleContent msdata:ColumnName="spirit_Text" msdata:Ordinal="0">
                                <xs:extension base="xs:string">
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="source" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="page" type="xs:string" minOccurs="1" maxOccurs="1" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="spirits">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="spirit">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="id" type="xs:string" />
                    <xs:element name="name" type="xs:string" />
                    <xs:element name="page" type="xs:unsignedShort" />
                    <xs:element name="source" type="xs:string" />
                    <xs:element name="bod" type="xs:string" />
                    <xs:element name="agi" type="xs:string" />
                    <xs:element name="rea" type="xs:string" />
                    <xs:element name="str" type="xs:string" />
                    <xs:element name="cha" type="xs:string" />
                    <xs:element name="int" type="xs:string" />
                    <xs:element name="log" type="xs:string" />
                    <xs:element name="wil" type="xs:string" />
                    <xs:element name="ini" type="xs:string" />
                    <xs:element minOccurs="0" name="edg" type="xs:string" />
                    <xs:element minOccurs="0" name="mag" type="xs:string" />
                    <xs:element minOccurs="0" name="res" type="xs:unsignedByte" />
                    <xs:element minOccurs="0" name="dep" type="xs:unsignedByte" />
                    <xs:element minOccurs="0" name="ess" type="xs:string" />
                    <xs:element minOccurs="0" name="bonus">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="enabletab">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="name" type="xs:string" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element minOccurs="0" name="optionalpowers">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="power" type="xs:string" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="powers">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="power">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute name="select" type="xs:string" use="optional" />
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="skills">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="skill">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute name="attr" type="xs:string" use="optional" />
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element minOccurs="0" name="weaknesses">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="weakness" type="xs:string" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:UseCurrentLocale="true">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="chummer" />
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== chummer5a/chummer5a/Chummer/data/streams.xml
<?xml version="1.0" encoding="utf-8"?>

<!--This file is part of Chummer5a.

    Chummer5a is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Chummer5a is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Chummer5a.  If not, see <http://www.gnu.org/licenses/>.

    You can obtain the full source code for Chummer5a at
    https://github.com/chummer5a/chummer5a
-->
<chummer xmlns="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.w3.org/2001/XMLSchema streams.xsd">
  <version>0</version>
  <traditions>
    <tradition>
      <id>7a3ecfbe-616e-425d-b204-329de37ffdbb</id>
      <name>Default</name>
      <drain>WIL + RES</drain>
      <spirits>
        <spirit>Courier Sprite</spirit>
        <spirit>Crack Sprite</spirit>
        <spirit>Data Sprite</spirit>
        <spirit>Fault Sprite</spirit>
        <spirit>Machine Sprite</spirit>
        <spirit>Companion Sprite</spirit>
        <spirit>Generalist Sprite</spirit>
      </spirits>
      <source>SR5</source>
      <page>258</page>
    </tradition>
  </traditions>
  <spirits>
    <!--Sprites Corebook-->
    <spirit>
      <id>acf0c123-0881-4f13-8a98-010516e74019</id>
      <name>Courier Sprite</name>
      <page>259</page>
      <source>SR5</source>
      <bod>0</bod>
      <agi>0</agi>
      <rea>0</rea>
      <str>0</str>
      <cha>F+0</cha>
      <int>F+3</int>
      <log>F+1</log>
      <wil>F+2</wil>
      <ini>(F*2)+1</ini>
      <powers>
        <power>Cookie</power>
        <power>Hash</power>
      </powers>
      <skills>
        <skill>Computer</skill>
        <skill>Hacking</skill>
      </skills>
    </spirit>
    <spirit>
      <id>610c00a4-7f11-4c88-8074-158f33aeccc0</id>
      <name>Crack Sprite</name>
      <page>259</page>
      <source>SR5</source>
      <bod>0</bod>
      <agi>0</agi>
      <rea>0</rea>
      <str>0</str>
      <cha>F+0</cha>
      <int>F+3</int>
      <log>F+2</log>
      <wil>F+1</wil>
      <ini>(F*2)+2</ini>
      <powers>
        <power>Suppression</power>
      </powers>
      <skills>
        <skill>Computer</skill>
        <skill>Electronic Warfare</skill>
        <skill>Hacking</skill>
      </skills>
    </spirit>
    <spirit>
      <id>61357134-dd63-442c-b532-355420b30b6e</id>
      <name>Data Sprite</name>
      <page>259</page>
      <source>SR5</source>
      <bod>0</bod>
      <agi>0</agi>
      <rea>0</rea>
      <str>0</str>
      <cha>F-1</cha>
      <int>F+0</int>
      <log>F+4</log>
      <wil>F+1</wil>
      <ini>(F*2)+4</ini>
      <powers>
        <power>Camouflage</power>
        <power>Watermark</power>
      </powers>
      <skills>
        <skill>Computer</skill>
        <skill>Electronic Warfare</skill>
      </skills>
    </spirit>
    <spirit>
      <id>c3be27c2-247c-4039-9529-2ff3b2e670ec</id>
      <name>Fault Sprite</name>
      <page>259</page>
      <source>SR5</source>
      <bod>0</bod>
      <agi>0</agi>
      <rea>0</rea>
      <str>0</str>
      <cha>F+3</cha>
      <int>F+0</int>
      <log>F+1</log>
      <wil>F+2</wil>
      <ini>(F*2)+1</ini>
      <powers>
        <power>Electron Storm</power>
      </powers>
      <skills>
        <skill>Computer</skill>
        <skill>Cybercombat</skill>
        <skill>Hacking</skill>
      </skills>
    </spirit>
    <spirit>
      <id>80bd0cd6-fcaa-49c2-a88f-c28b4eb28c61</id>
      <name>Machine Sprite</name>
      <page>259</page>
      <source>SR5</source>
      <bod>0</bod>
      <agi>0</agi>
      <rea>0</rea>
      <str>0</str>
      <cha>F+1</cha>
      <int>F+0</int>
      <log>F+3</log>
      <wil>F+2</wil>
      <ini>(F*2)+3</ini>
      <powers>
        <power>Diagnostics</power>
        <power>Gremlins</power>
        <power>Stability</power>
      </powers>
      <skills>
        <skill>Computer</skill>
        <skill>Electronic Warfare</skill>
        <skill>Hardware</skill>
      </skills>
    </spirit>
    <spirit>
      <id>74db183e-2fef-4e6d-84a3-63e641d93bf0</id>
      <name>Companion Sprite</name>
      <page>100</page>
      <source>KC</source>
      <bod>0</bod>
      <agi>0</agi>
      <rea>0</rea>
      <str>0</str>
      <cha>F-1</cha>
      <int>F+1</int>
      <log>F</log>
      <wil>F+4</wil>
      <ini>(F*2)</ini>
      <powers>
        <power>Bodyguard</power>
        <power>Shield</power>
      </powers>
      <skills>
        <skill>Computer</skill>
        <skill>Electronic Warfare</skill>
      </skills>
    </spirit>
    <spirit>
      <id>80788abc-4b14-40b0-8ffd-e36fe60653cb</id>
      <name>Generalist Sprite</name>
      <page>100</page>
      <source>KC</source>
      <bod>0</bod>
      <agi>0</agi>
      <rea>0</rea>
      <str>0</str>
      <cha>F+1</cha>
      <int>F+1</int>
      <log>F+1</log>
      <wil>F+1</wil>
      <ini>(F*2)+1</ini>
      <optionalpowers>
        <power>Cookie</power>
        <power>Hash</power>
        <power>Suppression</power>
        <power>Camouflage</power>
        <power>Watermark</power>
        <power>Electron Storm</power>
        <power>Diagnostics</power>
        <power>Gremlins</power>
        <power>Stability</power>
        <power>Bodyguard</power>
        <power>Shield</power>
      </optionalpowers>
      <skills>
        <skill>Computer</skill>
        <skill>Electronic Warfare</skill>
        <skill>Hacking</skill>
      </skills>
    </spirit>
  </spirits>
</chummer>
