=== chummer5a/chummer5a/Chummer/data/vehicles.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
  <xs:include schemaLocation="conditions.xsd" />

  <xs:element name="mods">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" nillable="true" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:simpleContent msdata:ColumnName="name_Text" msdata:Ordinal="1">
              <xs:extension base="xs:string">
                <xs:attribute name="rating" type="xs:string" />
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="hide" type="xs:string" minOccurs="0" maxOccurs="1" />
        <xs:element name="addslots" type="xs:string" minOccurs="0" />
        <xs:element ref="mod" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="weaponmountmods">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" nillable="true" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:simpleContent msdata:ColumnName="name_Text" msdata:Ordinal="1">
              <xs:extension base="xs:string">
                <xs:attribute name="rating" type="xs:string" />
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="hide" type="xs:string" minOccurs="0" maxOccurs="1" />
        <xs:element name="addslots" type="xs:string" minOccurs="0" />
        <xs:element ref="mod" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="chummer">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="categories" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="category" nillable="true" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent msdata:ColumnName="category_Text" msdata:Ordinal="0">
                    <xs:extension base="xs:string">
                      <xs:attribute name="blackmarket" type="xs:string" use="optional" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="modcategories" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="category" nillable="true" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent msdata:ColumnName="category_Text" msdata:Ordinal="0">
                    <xs:extension base="xs:string">
                      <xs:attribute name="blackmarket" type="xs:string" use="optional" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="limits" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="limit" nillable="true" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent msdata:ColumnName="category_Text" msdata:Ordinal="0">
                    <xs:extension base="xs:string">
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="vehicles" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="vehicle" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="id" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="page" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="source" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="accel" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="armor" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="avail" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="body" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="category" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="cost" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="handling" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="pilot" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="sensor" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="speed" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="bodymodslots" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="cyberwares" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="cyberware" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="name" minOccurs="0" maxOccurs="1" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="gears" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="gear" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="hide" minOccurs="0" maxOccurs="1" />
                    <xs:element name="mods" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="addslots" type="xs:integer" minOccurs="0" maxOccurs="1" />
                          <xs:element name="name" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute name="select" type="xs:string" use="optional" />
                                  <xs:attribute name="rating" type="xs:integer" use="optional" />
                                  <xs:attribute name="cost" type="xs:integer" use="optional" />
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="modslots" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="seats" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="weaponmodslots" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="weaponmounts" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="weaponmount" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="control" minOccurs="1" maxOccurs="1"/>
                                <xs:element name="flexibility" minOccurs="1" maxOccurs="1"/>
                                <xs:element name="size" minOccurs="1" maxOccurs="1"/>
                                <xs:element name="visibility" minOccurs="1" maxOccurs="1"/>
	                              <xs:element name="allowedweapons" type="xs:string" minOccurs="0" maxOccurs="1" />
	                              <xs:element name="mods" minOccurs="0" maxOccurs="unbounded">
		                              <xs:complexType>
			                              <xs:sequence>
				                              <xs:element name="mod" minOccurs="1" maxOccurs="unbounded"/>
			                              </xs:sequence>
		                              </xs:complexType>
	                              </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="weapons" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="weapon" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element ref="mods" minOccurs="0" maxOccurs="1" />
        <xs:element name="weaponmounts" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="weaponmount" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="id" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="hide" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="page" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="source" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="avail" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="category" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="cost" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="create" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="optionaldrone" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="slots" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element ref="forbidden" minOccurs="0" maxOccurs="1" />
                    <xs:element ref="required" minOccurs="0" maxOccurs="1" />
                    <xs:element name="weaponcategories" type="xs:string" minOccurs="0" maxOccurs="1" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element ref="weaponmountmods" minOccurs="0" maxOccurs="1" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:element name="mod">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="id" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
        <xs:element name="page" type="xs:string" minOccurs="1" maxOccurs="1" />
        <xs:element name="source" type="xs:string" minOccurs="1" maxOccurs="1" />
        <xs:element name="avail" type="xs:string" minOccurs="1" maxOccurs="1" />
        <xs:element name="category" type="xs:string" minOccurs="1" maxOccurs="1" />
        <xs:element name="cost" type="xs:string" minOccurs="1" maxOccurs="1" />
        <xs:element name="rating" type="xs:string" minOccurs="1" maxOccurs="1" />
        <xs:element name="slots" type="xs:string" minOccurs="1" maxOccurs="1" />
        <xs:element name="bonus" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="accel" type="xs:string" minOccurs="0" maxOccurs="1" />
              <xs:element name="armor" type="xs:string" minOccurs="0" maxOccurs="1" />
              <xs:element name="body" type="xs:string" minOccurs="0" maxOccurs="1" />
              <xs:element name="devicerating" type="xs:string" minOccurs="0" maxOccurs="1" />
              <xs:element name="handling" type="xs:string" minOccurs="0" maxOccurs="1" />
              <xs:element name="improvesensor" type="xs:string" minOccurs="0" maxOccurs="1" />
              <xs:element name="offroadaccel" type="xs:string" minOccurs="0" maxOccurs="1" />
              <xs:element name="offroadhandling" type="xs:string" minOccurs="0" maxOccurs="1" />
              <xs:element name="offroadspeed" type="xs:string" minOccurs="0" maxOccurs="1" />
              <xs:element name="pilot" type="xs:string" minOccurs="0" maxOccurs="1" />
              <xs:element name="seats" type="xs:string" minOccurs="0" maxOccurs="1" />
              <xs:element name="selecttext" type="xs:string" minOccurs="0" maxOccurs="1" />
              <xs:element name="sensor" type="xs:string" minOccurs="0" maxOccurs="1" />
              <xs:element name="speed" type="xs:string" minOccurs="0" maxOccurs="1" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="ammobonus" type="xs:string" minOccurs="0" maxOccurs="1" />
        <xs:element name="ammoreplace" type="xs:string" minOccurs="0" maxOccurs="1" />
        <xs:element name="capacity" type="xs:string" minOccurs="0" maxOccurs="1" />
        <xs:element name="conditionmonitor" type="xs:string" minOccurs="0" maxOccurs="1" />
        <xs:element name="downgrade" minOccurs="0" maxOccurs="1" />
        <xs:element name="firewall" type="xs:integer" minOccurs="0" maxOccurs="1" />
        <xs:element name="hide" minOccurs="0" maxOccurs="1" />
        <xs:element name="limit" type="xs:string" minOccurs="0" maxOccurs="1" />
        <xs:element name="minrating" type="xs:string" minOccurs="0" maxOccurs="1" />
        <xs:element name="optionaldrone" minOccurs="0" maxOccurs="1" />
        <xs:element name="pilot" type="xs:integer" minOccurs="0" maxOccurs="1" />
        <xs:element ref="required" minOccurs="0" maxOccurs="1" />
        <xs:element name="subsystems" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="subsystem" nillable="true" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent msdata:ColumnName="subsystem_Text" msdata:Ordinal="0">
                    <xs:extension base="xs:string">
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="weaponmountcategories" type="xs:string" minOccurs="0" maxOccurs="1" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:UseCurrentLocale="true">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="mods" />
        <xs:element ref="chummer" />
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== chummer5a/chummer5a/Chummer/customdata/Add Schattenload Items/custom_vehicles.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--This file is part of Chummer5a.

    Chummer5a is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Chummer5a is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Chummer5a.  If not, see <http://www.gnu.org/licenses/>.

    You can obtain the full source code for Chummer5a at
    https://github.com/chummer5a/chummer5a
-->
<chummer xmlns="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.w3.org/2001/XMLSchema vehicles.xsd">
  <vehicles>
    <vehicle>
      <id>d2336327-1f36-479f-94f2-62a359c0dcbd</id>
      <name>Sony Economically-4</name>
      <category>Drones: Anthro</category>
      <page>3</page>
      <source>SL03.19</source>
      <handling>2</handling>
      <speed>3</speed>
      <accel>1</accel>
      <body>3</body>
      <armor>0</armor>
      <pilot>3</pilot>
      <sensor>3</sensor>
      <cost>18000</cost>
      <avail>4</avail>
      <gears>
        <gear>
          <name>Sensor Array</name>
          <rating>3</rating>
          <maxrating>6</maxrating>
        </gear>
      </gears>
      <mods>
        <name>Drone Arm</name>
        <name>Drone Arm</name>
        <name>Drone Leg</name>
        <name>Drone Leg</name>
      </mods>
    </vehicle>
    <vehicle>
      <id>21116c38-076e-4f99-9e0b-6083f8a9c83a</id>
      <name>Sony Reliable-4</name>
      <category>Drones: Anthro</category>
      <page>3</page>
      <source>SL03.19</source>
      <handling>2</handling>
      <speed>3</speed>
      <accel>2</accel>
      <body>4</body>
      <armor>3</armor>
      <pilot>4</pilot>
      <sensor>4</sensor>
      <cost>34000</cost>
      <avail>12R</avail>
      <gears>
        <gear>
          <name>Sensor Array</name>
          <rating>4</rating>
          <maxrating>6</maxrating>
        </gear>
        <gear>
          <name>Quick-Draw Holster</name>
        </gear>
      </gears>
      <mods>
        <name>Drone Arm</name>
        <name>Drone Arm</name>
        <name>Drone Leg</name>
        <name>Drone Leg</name>
        <name>Emotive Display</name>
      </mods>
      <weaponmounts>
        <weaponmount>
          <control>Remote</control>
          <flexibility>Fixed</flexibility>
          <size>Standard (Drone)</size>
          <visibility>External</visibility>
          <allowedweapons>Underarm Ballistic Shield</allowedweapons>
        </weaponmount>
        <weaponmount>
          <control>Remote</control>
          <flexibility>Fixed</flexibility>
          <size>Standard (Drone)</size>
          <visibility>External</visibility>
          <allowedweapons>Gas Grenade Launcher</allowedweapons>
        </weaponmount>
      </weaponmounts>
      <weapons>
        <weapon>
          <name>Gas Grenade Launcher</name>
        </weapon>
        <weapon>
          <name>Underarm Ballistic Shield</name>
        </weapon>
      </weapons>
    </vehicle>
    <vehicle>
      <id>dac6f24b-a8e1-4d83-bc43-27ee02b0963a</id>
      <name>Sony Versatile Cologne Ed.</name>
      <category>Drones: Anthro</category>
      <page>3</page>
      <source>SL03.19</source>
      <handling>2</handling>
      <speed>3</speed>
      <accel>1</accel>
      <body>3</body>
      <armor>0</armor>
      <pilot>3</pilot>
      <sensor>3</sensor>
      <cost>23000</cost>
      <avail>18R</avail>
      <gears>
        <gear>
          <name>Sensor Array</name>
          <rating>3</rating>
          <maxrating>6</maxrating>
        </gear>
      </gears>
      <mods>
        <name>Drone Arm</name>
        <name>Drone Arm</name>
        <name>Drone Leg</name>
        <name>Drone Leg</name>
      </mods>
      <weaponmounts>
        <weaponmount>
          <control>Remote</control>
          <flexibility>Fixed</flexibility>
          <size>Standard (Drone)</size>
          <visibility>External</visibility>
          <allowedweapons>Caramel Bonbon Grenade Launcher</allowedweapons>
        </weaponmount>
      </weaponmounts>
      <weapons>
        <weapon>
          <name>Caramel Bonbon Grenade Launcher</name>
        </weapon>
      </weapons>
    </vehicle>
    <vehicle>
      <id>cbd915a6-8ab8-4509-b70f-a2cd27803a1e</id>
      <name>Sony Orderly-4</name>
      <category>Drones: Anthro</category>
      <page>3</page>
      <source>SL03.19</source>
      <handling>4</handling>
      <speed>3</speed>
      <accel>1</accel>
      <body>4</body>
      <armor>3</armor>
      <pilot>4</pilot>
      <sensor>4</sensor>
      <cost>38000</cost>
      <avail>11R</avail>
      <gears>
        <gear>
          <name>Sensor Array</name>
          <rating>4</rating>
          <maxrating>6</maxrating>
        </gear>
      </gears>
      <mods>
        <name>Drone Arm</name>
        <name>Drone Arm</name>
        <name>Drone Leg</name>
        <name>Drone Leg</name>
        <name>Emotive Display</name>
      </mods>
    </vehicle>
<!--Region Der Multimog-->
    <vehicle>
      <id>1b27cddf-25fb-46a0-aff0-c252231ac616</id>
      <name>Mercedes Multimog-D1</name>
      <page>1</page>
      <source>SL07.19</source>
      <accel>1</accel>
      <armor>16</armor>
      <avail>0</avail>
      <body>16</body>
      <category>Trucks</category>
      <cost>45000</cost>
      <handling>3/4</handling>
      <pilot>1</pilot>
      <sensor>2</sensor>
      <speed>3</speed>
      <bodymodslots>4</bodymodslots>
      <gears>
        <gear>
          <name>Sensor Array</name>
          <rating>2</rating>
          <maxrating>7</maxrating>
        </gear>
      </gears>
      <seats>6</seats>
    </vehicle>
    <vehicle>
      <id>6a612d60-2776-4556-8b56-9e781241005d</id>
      <name>Mercedes Multimog-K4 "Greif"</name>
      <page>1</page>
      <source>SL07.19</source>
      <accel>1</accel>
      <armor>18</armor>
      <avail>12</avail>
      <body>18</body>
      <category>Trucks</category>
      <cost>83000</cost>
      <handling>3/4</handling>
      <pilot>1</pilot>
      <sensor>4</sensor>
      <speed>3</speed>
      <bodymodslots>4</bodymodslots>
      <gears>
        <gear>
          <name>Sensor Array</name>
          <rating>3</rating>
          <maxrating>7</maxrating>
        </gear>
      </gears>
      <mods>
        <name>Rigger Adaptation</name>
        <name rating="4">ECM</name>
        <name>Satellite Link</name>
        <name>Landing Drone Rack (Small)</name>
        <name>Landing Drone Rack (Small)</name>
      </mods>
      <seats>6</seats>
    </vehicle>
  </vehicles>
<!--Mods-->
  <mods>
    <mod>
      <id>a8673414-5ad8-441c-bcea-65a93ab3d8c4</id>
      <name>Emotive Display</name>
      <page>3</page>
      <source>SL03.19</source>
      <avail>0</avail>
      <category>Cosmetic</category>
      <cost>0</cost>
      <rating>0</rating>
      <slots>0</slots>
    </mod>
  </mods>
</chummer>

=== chummer5a/chummer5a/Chummer/customdata/ShadowNET Rules/amend_vehicles.xml
<?xml version="1.0" encoding="utf-8"?>
<!--This file is part of Chummer5a.

    Chummer5a is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Chummer5a is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Chummer5a.  If not, see <http://www.gnu.org/licenses/>.

    You can obtain the full source code for Chummer5a at
    https://github.com/chummer5a/chummer5a
-->
<chummer xmlns="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/XMLSchema vehicles.xsd">
  <vehicles>
    <vehicle>
      <name>Horizon Noizquito (Microdrone)</name> <!-- Not in Player Rules -->
      <hide />
    </vehicle>
	  <vehicle>
      <name>Medusa Extensions (Mini)</name>
      <hide />
    </vehicle>

<!-- TODO: Handle GTS Tower, it should have a retrans unit and a drone landing rack -->
    <vehicle>
      <name>GTS Tower (Large)</name>
      <mods remove="yes" />
      <mods>
        <name>Landing Drone Rack (Mini)</name>
        <name>Landing Drone Rack (Mini)</name>
        <name>Landing Drone Rack (Mini)</name>
        <name>Landing Drone Rack (Mini)</name>
        <name>Retrans Unit</name>
      </mods>
    </vehicle>

    <vehicle>
      <name>Avibras-Nissan AN 822</name>
      <accel>3</accel>
<!--      <gears>
        <gear rating="2" maxrating="3">Sensor Array</gear>
      </gears> -->
    </vehicle>
  </vehicles>
  <mods>
    <!-- Weapon Mounts from Core -->
    <mod>
      <name>Weapon Mount</name>
      <hide />
    </mod>
    <mod>
      <name>Heavy Weapon Mount</name>
      <hide />
    </mod>
    <mod>
      <name>Manual Operation</name>
      <hide />
    </mod>
    <!-- End -->
    <!-- Stolen Souls modifications -->
    <mod>
      <name>Chameleon Coating[Stolen Souls]</name>
      <hide />
    </mod>
    <mod>
      <name>Dash Light Bar</name>
      <hide />
    </mod>
    <mod>
      <name>Emergency Light Bar</name>
      <hide />
    </mod>
    <mod>
      <name>Siren</name>
      <hide />
    </mod>
    <mod>
      <name>Smuggling Compartment (Dwarf, Human, Elf, or Ork)</name>
      <hide />
    </mod>
    <mod>
      <name>Smuggling Compartment (Troll)</name>
      <hide />
    </mod>
    <!-- End -->
    <mod>
      <name>Yerz Kit</name>
      <hide />
    </mod>
  </mods>
</chummer>
